build: Windows Meson builds do not resolve zlib dependency.
Commit 32d6a76b ("build: Use Meson's find_library() for MSVC builds as
needed") introduced a Meson MSVC bug that prevents the zlib subproject
from being used when pkg-config fails to find it first.

During a compilation the user will see the following error:

[89/197] Compiling C object gio/gio-2.0@sha/gzlibcompressor.c.obj.
FAILED: gio/gio-2.0@sha/gzlibcompressor.c.obj
cl @gio/gio-2.0@sha/gzlibcompressor.c.obj.rsp
c:\users\XXXXXX\src\glib\gio\gzlibcompressor.c(26): fatal error C1083: Can
not open include file: 'zlib.h': No such file or directory
[98/197] Compiling C object gio/gio-2.0@sha/gthreadedresolver.c.obj.
ninja: build stopped: subcommand failed.